# Generated by Django 2.0.6 on 2018-06-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='servers',
        ),
    ]
