# Generated by Django 2.0.6 on 2018-06-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='服务器地址')),
                ('game', models.CharField(max_length=30, verbose_name='游戏名')),
                ('area', models.CharField(max_length=30, verbose_name='游戏区服')),
                ('version', models.CharField(default='v1.0', max_length=30, verbose_name='游戏版本')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最近编辑时间')),
            ],
            options={
                'verbose_name': '服务器信息',
                'verbose_name_plural': '服务器信息',
                'ordering': ['last_update'],
            },
        ),
    ]
