# Generated by Django 2.0.6 on 2018-06-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='服务器地址')),
                ('game', models.CharField(max_length=30, verbose_name='游戏名')),
                ('area', models.CharField(max_length=30, verbose_name='游戏区服')),
            ],
        ),
    ]
