# Generated by Django 2.0.6 on 2018-06-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最近编辑时间'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True, verbose_name='服务器地址'),
        ),
    ]
