# Generated by Django 2.0.6 on 2018-06-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0002_auto_20180610_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='test',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
