# Generated by Django 2.0.6 on 2018-06-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0003_server_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='test',
        ),
    ]
