# Generated by Django 2.0.6 on 2018-06-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0004_remove_server_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='version',
            field=models.CharField(default='v1.0', max_length=30, verbose_name='游戏版本'),
        ),
    ]
